language: cpp

compiler:
  - gcc


platform:
  - x64

configuration:
  - Release

before_install:
  - sudo add-apt-repository -y ppa:wxformbuilder/wxwidgets
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  
install:
  - sudo apt-get install libwxgtk3.0-dev g++-4.8 libstdc++-4.8-dev libcairo2-dev 
  - export CXX="g++-4.8"
  - echo "CXX=$CXX"
  - echo "version `$CXX --version`"

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DTESTS=0 ..
  - make
