sudo: false
dist: trusty

language: cpp

compiler:
  - gcc

platform:
  - x64

configuration:
  - Release
  
notifications:
  email: false

addons:
  apt:
    packages:
    - libwxgtk3.0-dev
    - libcairo2-dev

install:
  - wget -P tests https://raw.githubusercontent.com/philsquared/Catch/master/single_include/catch.hpp

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - ./tests/tests
