language: cpp

compiler:
  - gcc

platform:
  - x64

configuration:
  - Release
  
notifications:
  email: false
  
install:
  - sudo apt-get install libwxgtk3.0-dev g++-4.8 libstdc++-4.8-dev libcairo2-dev 
  - wget -P tests https://github.com/catchorg/Catch2/releases/download/v2.0.1/catch.hpp

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - ./tests/tests
